[package]
name = "zead0n/component"
description = "A simplified version of sleitnik's Component util"
version = "0.1.1"
licence = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "sleitnick/signal@^2"
Trove = "sleitnick/trove@^1"
Promise = "lukadev-0/typed-promise@^4"
