[package]
name = "zead0n/loader"
description = "A modification sleitnick's Loader utility with some spice."
version = "0.1.0"
licence = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
